# opennem logging setup and config
version: 1
disable_existing_loggers: true

formatters:
  basic:
    format: "[%(name)-35s %(levelname)8s] %(message)s"
  standard:
    format: "[%(asctime)s] {%(pathname)s:%(lineno)d} %(levelname)s - %(message)s"
    datefmt: "%H:%M:%S"
  clean:
    format: "%(message)s"

handlers:
  console: # handler which will log into stdout
    class: logging.StreamHandler
    level: DEBUG
    formatter: basic
    stream: ext://sys.stdout
  file_debug:
    class: logging.FileHandler
    level: DEBUG
    formatter: standard
    filename: debug-run.log
  file_archive:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: standard # Use formatter defined above
    filename: opennem.log
    maxBytes: 10485760 # 10MB
    backupCount: 10
    encoding: utf8

root:
  level: ERROR
  handlers: [console, file_debug]

  # Defines descendants of root logger
loggers:
  opennem:
    level: DEBUG
    handlers: [console, file_debug]
    propagate: no
  opennem.cli:
    level: INFO
    handlers: [console]
    propagate: no
  opennem.diff:
    level: DEBUG
    handlers: [console]
    propagate: no
