"""
find bad DUID data

"""

from opennem.cms.importer import get_cms_facilities

_REL_DUIDS = [
    "ADPBA1G",
    "ADPBA1L",
    "ADPMH1",
    "ADPPV1",
    "ADPPV2",
    "ADPPV3",
    "ANGAST1",
    "APPIN",
    "ARWF1",
    "AVLSF1",
    "BDL01",
    "BDL02",
    "BAKING1",
    "BALDHWF1",
    "BBASEHOS",
    "BANGOWF1",
    "BANGOWF2",
    "BAPS",
    "BANN1",
    "BARCALDN",
    "BARCSF1",
    "BARKIPS1",
    "BLNKTAS",
    "BLNKVIC",
    "BASTYAN",
    "BW01",
    "BW02",
    "BW03",
    "BW04",
    "BBTHREE1",
    "BBTHREE2",
    "BBTHREE3",
    "TVPP104",
    "BRYB2WF2",
    "BRYB1WF1",
    "BERYLSF1",
    "BLOWERNG",
    "BLUEGSF1",
    "BLYTHB1",
    "BOCORWF1",
    "BODWF1",
    "MCKAY1",
    "BOLIVPS1",
    "BOLIVAR1",
    "BOWWBA1G",
    "BOWWBA1L",
    "BOWWDG1",
    "BOWWPV1",
    "BOMENSF1",
    "BBATRYL1",
    "BBATTERY",
    "BRAEMAR5",
    "BRAEMAR6",
    "BRAEMAR7",
    "BRAEMAR1",
    "BRAEMAR2",
    "BRAEMAR3",
    "BWTR1",
    "BHBG1",
    "BHBL1",
    "GB01",
    "BROKENH1",
    "BROOKLYN",
    "BROWNMT",
    "BPLANDF1",
    "BULBESG1",
    "BULBESL1",
    "BULGANA1",
    "BNGSF1",
    "BNGSF2",
    "BDONGHYD",
    "BURRIN",
    "BUTLERSG",
    "CNUNDAWF",
    "CAPBES1G",
    "CAPBES1L",
    "CESF1",
    "CATHROCK",
    "CTHLWF1",
    "CETHANA",
    "CHALLHWF",
    "CHPSTWF1",
    "CHYTWF1",
    "CHILDSF1",
    "CHBESSG1",
    "CHBESSL1",
    "CBWWBA1G",
    "CBWWBA1L",
    "CBWWBG1",
    "CBWWDG1",
    "CBWWDG2",
    "CBWWPV1",
    "CBWWPV2",
    "CLARESF1",
    "CLRKCWF1",
    "CLAYTON",
    "CLEMGPWF",
    "CLERMSF1",
    "CLOVER",
    "CLUNY",
    "CODRNGTON",
    "COHUNSF1",
    "COLEASF1",
    "COLWF01",
    "CSPVPS1",
    "CG1",
    "CG2",
    "CG3",
    "CG4",
    "COLUMSF1",
    "CPSA",
    "CONDONG1",
    "CBWF1",
    "COOPGWF1",
    "COPTNHYD",
    "CRWASF1",
    "CROOKWF2",
    "CROOKWF3",
    "CROWLWF1",
    "CRURWF1",
    "CULLRGWF",
    "DALNTH1",
    "DDPS1",
    "DDSF1",
    "DARLSF1",
    "DARTM1",
    "DAYDSF1",
    "DIAPURWF1",
    "DRYCGT1",
    "DRYCGT2",
    "DRYCGT3",
    "DULAWF1",
    "DUNDWF1",
    "DUNDWF2",
    "DUNDWF3",
    "EASTCRK2",
    "EASTCRK",
    "EDENVSF1",
    "EILDON1",
    "EILDON2",
    "EILDON3",
    "ELAINWF1",
    "EMERASF1",
    "ER01",
    "ER02",
    "ER03",
    "ER04",
    "ERGT01",
    "FNWF1",
    "FSWF1",
    "FINLYSF1",
    "FISHER",
    "FLYCRKWF",
    "GANGARR1",
    "GANNB1",
    "GANNSF1",
    "GERMCRK",
    "GIRGSF",
    "GSTONE1",
    "GSTONE2",
    "GSTONE3",
    "GSTONE4",
    "GSTONE5",
    "GSTONE6",
    "GLBWNHYD",
    "GLENMAG1",
    "GLENNCRK",
    "GLENSF1",
    "GLRWNSF1",
    "GPWFEST1",
    "GPWFEST2",
    "GPWFEST3",
    "GOONSF1",
    "GORDON",
    "GSWF1A",
    "GSWF1B1",
    "GRANGEAV",
    "GRANWF1",
    "GRIFSF1",
    "GROSV1",
    "GROSV2",
    "GULLRSF1",
    "GULLRWF1",
    "GULLRWF2",
    "GNNDHSF1",
    "GUNNING1",
    "GUTHEGA",
    "HALAMRD1",
    "HALLWF1",
    "HALLWF2",
    "AGLHAL",
    "HAMISF1",
    "HVWWBA1G",
    "HVWWBA1L",
    "HVWWPV1",
    "HASTING3",
    "HAUGHT11",
    "HD1WF1",
    "HAYMSF1",
    "HBESSG1",
    "HBESSL1",
    "HEPWIND1",
    "HILLSTN1",
    "HPRG1",
    "HPRL1",
    "HDWF1",
    "HDWF2",
    "HDWF3",
    "HUGSF1",
    "HUMENSW",
    "HUMEV",
    "HEZ1",
    "INVICTA",
    "ICSM",
    "JACKSGUL",
    "JLA01",
    "JLA02",
    "JLA03",
    "JLA04",
    "JLB01",
    "JLB02",
    "JLB03",
    "JEMALNG1",
    "JNDABNE1",
    "JBUTTERS",
    "JOUNAMA1",
    "JUNEESF1",
    "KABANWF1",
    "KARSF1",
    "KAREEYA1",
    "KAREEYA2",
    "KAREEYA3",
    "KAREEYA4",
    "KAREEYA5",
    "KEEPIT",
    "KEPSF1",
    "KEPWF1",
    "KEPBG1",
    "KEPBL1",
    "KIAMSF1",
    "KIATAWF1",
    "KSP1",
    "KINGASF1",
    "LADBROK1",
    "LADBROK2",
    "LBBG1",
    "LBBL1",
    "LKBONNY2",
    "LKBONNY3",
    "LKBONNY1",
    "LNGS1",
    "LNGS2",
    "LILYSF1",
    "LIMOSF11",
    "LIMOSF21",
    "LGAPWF1",
    "LGAPWF2",
    "LRSF1",
    "LONSDALE",
    "LYA1",
    "LYA2",
    "LYA3",
    "LYA4",
    "LOYYB1",
    "LOYYB2",
    "LUCAS2S2",
    "LUCASHGT",
    "MACARTH1",
    "MCINTYR1",
    "MACKNTSH",
    "MANSLR1",
    "MAPS2PV1",
    "MAPS3PV1",
    "MANNSF2",
    "MAROOWF1",
    "MARYRSF1",
    "MEADOWBK",
    "METZSF1",
    "MIDDLSF1",
    "MINTARO",
    "MOLNGSF1",
    "MOORAWF1",
    "MORANBAH",
    "MBAHNTH",
    "MOREESF1",
    "MWPS4PV1",
    "MORTLK11",
    "MORTLK12",
    "MRTLSWF1",
    "MLWF1",
    "MEWF1",
    "MOUSF1",
    "MTGELWF1",
    "MERCER01",
    "MTMILLAR",
    "MP1",
    "MP2",
    "MSTUART1",
    "MSTUART2",
    "MSTUART3",
    "MLLFGEF1",
    "MLSP1",
    "MUWAWF1",
    "MUWAWF2",
    "MBPS2PV1",
    "MURRAY",
    "MUSSELR1",
    "NASF1",
    "NEVERSF1",
    "NEWENSF1",
    "NEWENSF2",
    "NPS",
    "NBHWF1",
    "NUMURSF1",
    "NYNGAN1",
    "OAKEY1SF",
    "OAKEY2SF",
    "OAKEY1",
    "OAKEY2",
    "OAKLAND1",
    "OAKY2",
    "OAKYCREK",
    "PALOONA",
    "PARSF1",
    "PPCCGT",
    "PIBESSG1",
    "PIBESSL1",
    "PINDARI",
    "POAT110",
    "POAT220",
    "PAREPS1",
    "PAREPW1",
    "POR01",
    "POR03",
    "PTSTAN1",
    "QPS1",
    "QPS2",
    "QPS3",
    "QPS4",
    "QPS5",
    "QBYNBG1",
    "QBYNBL1",
    "RACOMIL1",
    "RANGEB1",
    "REECE1",
    "REECE2",
    "REPULSE",
    "RESS1G",
    "RESS1L",
    "RPCG",
    "RRSF1",
    "ROWALLAN",
    "ROYALLA1",
    "RUBICON",
    "RUGBYR1",
    "RYANCWF1",
    "RYEPARK1",
    "SALTCRK1",
    "SAPHWF1",
    "SEBSF1",
    "SHEP1",
    "SHGEN",
    "SHPUMP",
    "SHOAL1",
    "STWF1",
    "SITHE01",
    "SNAPPER1",
    "SNOWSTH1",
    "SNOWNTH1",
    "SNOWTWN1",
    "SNUG1",
    "SNUG2",
    "SNUG3",
    "SNUGNL1",
    "AGLSOM",
    "HLMSEW01",
    "SKSF1",
    "STAPYLTON1",
    "STARHLWF",
    "STOCKYD1",
    "SMCSF1",
    "SUNRSF1",
    "SUNTPSF1",
    "SRSF1",
    "TABMILL2",
    "TAHMOOR1",
    "TB2BG1",
    "TB2BL1",
    "TB2SF1",
    "TBSF1",
    "TALWA1",
    "TALWB1",
    "TVCC201",
    "TARALGA1",
    "TNPS1",
    "TARRALEA",
    "TATIARA1",
    "TATURA01",
    "BLUFF1",
    "THEDROP1",
    "TIMWEST",
    "TOORAWF",
    "TIBG1",
    "TIBL1",
    "TORRB1",
    "TORRB2",
    "TORRB3",
    "TORRB4",
    "TOWER",
    "YABULU",
    "YABULU2",
    "TGNSS1",
    "TREVALLN",
    "TRIBUTE",
    "TULLYSM1",
    "TUMUT3",
    "SNOWYP",
    "UPPTUMUT",
    "TUNGATIN",
    "URANQ11",
    "URANQ12",
    "URANQ13",
    "URANQ14",
    "VALDORA1",
    "VP5",
    "VP6",
    "VPGS1",
    "VPGS2",
    "VPGS3",
    "VPGS4",
    "VPGS5",
    "VPGS6",
    "TITREE",
    "VBBG1",
    "VBBL1",
    "WAGGNSF1",
    "WLWLSF1",
    "WLWLSF2",
    "WALGRVG1",
    "WALGRVL1",
    "WANDB1",
    "WANDSF1",
    "WTAHB1",
    "WARWSF1",
    "WARWSF2",
    "WATERLWF",
    "WPWF",
    "WAUBRAWF",
    "WELNSF1",
    "WEMENSF1",
    "WESTILL1",
    "WKIEWA1",
    "WKIEWA2",
    "WSTWYSF1",
    "WDBESSG1",
    "WDBESSL1",
    "WDGPH1",
    "WESTCBT1",
    "WRSF1",
    "WRWF1",
    "WHITSF1",
    "WHIT1",
    "WILGB01",
    "WILGAPK",
    "WILLHOV1",
    "WGWF1",
    "WHILL1",
    "WINTSF1",
    "PUMP1",
    "PUMP2",
    "WOLLERT1",
    "WONWP",
    "WDLNGN01",
    "WOODLWN1",
    "WOOLNTH1",
    "WOOLGSF1",
    "WYASF1",
    "WYANGALA",
    "WYANGALB",
    "YWPS1",
    "YWPS2",
    "YWPS3",
    "YWPS4",
    "YSWF1",
    "YAMBUKWF",
    "YARANSF1",
    "YWNGAHYD",
    "YATSF1",
    "YAWWF1",
    "YENDWF1",
    "BALB1",
    "QBYNB1",
    "RIVNB2",
    "DPNTB1",
    "PIBESS1",
    "HBESS1",
    "ADPBA1",
    "CBWWBA1",
    "HVWWBA1",
    "BOWWBA1",
    "VBB1",
    "BULBES1",
    "WALGRV1",
    "LBB1",
]


_gi_duids = [
    "DUID",
    "CBESS1",
    "CLRKCWF1",
    "CLRKCWF2",
    "GIRGSF",
    "GSWF1A",
    "GSWF1B",
    "QPSF",
    "QPBESS",
    "SEBSF1",
    "WLWLSF1",
    "WLWLSF2",
    "WARATAH",
    "WELNSF1",
    "WDBESS",
    "WOLARSF1",
    "WUNUSF1",
]

_STORAGE_FUELTECHS = ["battery", "battery_charging", "battery_discharging"]


def _has_storage(unit):
    if unit.fueltech_id in _STORAGE_FUELTECHS:
        return True if unit.storage_capacity else False

    return "NA"


def _has_closure_date(unit):
    if not unit.status_id == "retired":
        return "NA"

    return True if unit.closure_date else False


async def check_duid_data():
    facilities = await get_cms_facilities()

    csv_field_data = []

    for facility in facilities:
        fac_record = {
            "code": facility.code,
            "name": facility.name,
            "network_id": facility.network_id,
            "network_region": facility.network_region,
            "has_description": True if facility.description else False,
            "has_location": True if facility.location else False,
            "has_photos": True if facility.photos else False,
        }

        for unit in facility.units:
            unit_record = {
                "unit_code": unit.code,
                "fueltech_id": unit.fueltech_id.value,
                "status_id": unit.status_id.value,
                "dispatch_type": unit.dispatch_type.value,
                "has_capacity": True if unit.capacity_registered else False,
                "has_capacity_max": True if unit.capacity_maximum else False,
                "has_storage_capacity": _has_storage(unit),
                "has_emissions_intensity": True if unit.emissions_factor_co2 else False,
                "has_expected_closure_date": True if unit.expected_closure_date else False,
                "has_commencement_date": True if unit.commencement_date else False,
                "has_closure_date": _has_closure_date(unit),
            }

            csv_field_data.append({**fac_record, **unit_record})

    return csv_field_data


if __name__ == "__main__":
    csv_field_data = check_duid_data()

    # sort by code
    csv_field_data = sorted(csv_field_data, key=lambda x: x["code"])

    # convert csv field data to csv
    import csv

    with open("duid_data.csv", "w") as f:
        writer = csv.DictWriter(f, fieldnames=csv_field_data[0].keys())
        writer.writeheader()
        writer.writerows(csv_field_data)
