LOGGING_CONFIG = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "basic": {"format": "[%(asctime)s] %(name)-35s %(levelname)8s] %(message)s"},
        "standard": {"format": "[%(asctime)s] {%(pathname)s:%(lineno)d} %(levelname)s - %(message)s", "datefmt": "%H:%M:%S"},
        "clean": {"format": "%(message)s"},
    },
    "handlers": {
        "console": {"class": "logging.StreamHandler", "level": "DEBUG", "formatter": "basic", "stream": "ext://sys.stdout"}
    },
    "root": {"level": "ERROR", "handlers": ["console"]},
    "loggers": {
        "opennem": {"level": "ERROR", "handlers": ["console"], "propagate": False},
        "opennem.cli": {"level": "INFO", "handlers": ["console"], "propagate": False},
        "opennem.diff": {"level": "DEBUG", "handlers": ["console"], "propagate": False},
        "shapely.geos": {"level": "INFO"},
        "urllib3": {"level": "ERROR"},
        "boto3": {"level": "ERROR"},
        "botocore": {"level": "ERROR"},
        "parso": {"level": "ERROR", "propagate": False},
        "matplotlib": {"level": "WARNING"},
        "psycopg.pq": {"level": "INFO"},
        "httpcore.http11": {"level": "ERROR"},
        "httpcore.connection": {"level": "ERROR"},
        "aiobotocore": {"level": "ERROR"},
        "aioboto3": {"level": "ERROR"},
        "instructor": {"level": "ERROR"},
        "httpx": {"level": "ERROR"},
        "openai": {"level": "ERROR"},
        "arq.worker": {"level": "INFO"},
        "clickhouse_connect": {"level": "INFO"},
        "httpcore.proxy": {"level": "INFO"},
    },
}
