# pylint: disable=no-member
"""
Generate migration diff

Revision ID: 0995118b97ec
Revises: c55917f188a5
Create Date: 2021-04-10 18:21:07.965211

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0995118b97ec"
down_revision = "c55917f188a5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("network", "network_price", existing_type=sa.TEXT(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("network", "network_price", existing_type=sa.TEXT(), nullable=True)
    # ### end Alembic commands ###
