# pylint: disable=no-member
"""
period field on milestones

Revision ID: 1485ce197dbd
Revises: 8e4fb8e5135a
Create Date: 2024-02-15 09:54:53.144810

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "1485ce197dbd"
down_revision = "8e4fb8e5135a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("milestones", sa.Column("period", sa.String(), nullable=True))
    op.alter_column(
        "milestones",
        "interval",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    op.drop_index("ix_milestones_dtime", table_name="milestones")
    op.create_index(op.f("ix_milestones_interval"), "milestones", ["interval"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_milestones_interval"), table_name="milestones")
    op.create_index("ix_milestones_dtime", "milestones", ["interval"], unique=False)
    op.alter_column(
        "milestones",
        "interval",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.drop_column("milestones", "period")
    # ### end Alembic commands ###
