# pylint: disable=no-member
"""
Add NPI pollution tracking with improved schema

Revision ID: 27431059b549
Revises: 9436b8ba01e9
Create Date: 2025-08-20 12:46:34.618226

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '27431059b549'
down_revision = '9436b8ba01e9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('npi_facilities',
    sa.Column('npi_id', sa.String(length=50), nullable=False),
    sa.Column('npi_name', sa.Text(), nullable=False),
    sa.Column('registered_business_name', sa.Text(), nullable=True),
    sa.Column('abn', sa.String(length=20), nullable=True),
    sa.Column('acn', sa.String(length=20), nullable=True),
    sa.Column('site_latitude', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('site_longitude', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('location_state', sa.String(length=3), nullable=True),
    sa.Column('site_address_suburb', sa.Text(), nullable=True),
    sa.Column('site_address_postcode', sa.String(length=10), nullable=True),
    sa.Column('company_website', sa.Text(), nullable=True),
    sa.Column('number_of_employees', sa.Integer(), nullable=True),
    sa.Column('main_activities', sa.Text(), nullable=True),
    sa.Column('report_year', sa.Integer(), nullable=False),
    sa.Column('data_start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('npi_id')
    )
    op.create_index('idx_npi_facilities_state', 'npi_facilities', ['location_state'], unique=False)
    op.create_index('idx_npi_facilities_year', 'npi_facilities', ['report_year'], unique=False)
    op.create_table('npi_substances',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('npi_name', sa.Text(), nullable=False),
    sa.Column('cas_number', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('code'),
    sa.UniqueConstraint('npi_name')
    )
    op.create_table('npi_pollution',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('npi_facility_id', sa.String(length=50), nullable=False),
    sa.Column('substance_code', sa.String(length=50), nullable=False),
    sa.Column('report_year', sa.Integer(), nullable=False),
    sa.Column('pollution_category', sa.String(length=20), nullable=False),
    sa.Column('pollution_subcategory', sa.String(length=20), nullable=True),
    sa.Column('pollution_value', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('pollution_unit', sa.String(length=10), nullable=True),
    sa.Column('data_quality', sa.String(length=50), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['npi_facility_id'], ['npi_facilities.npi_id'], ),
    sa.ForeignKeyConstraint(['substance_code'], ['npi_substances.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('npi_facility_id', 'substance_code', 'report_year', 'pollution_category', 'pollution_subcategory', name='uq_npi_pollution_facility_substance_year_category')
    )
    op.create_index('idx_npi_pollution_facility_year', 'npi_pollution', ['npi_facility_id', 'report_year'], unique=False)
    op.create_index('idx_npi_pollution_substance', 'npi_pollution', ['substance_code'], unique=False)
    op.create_index('idx_npi_pollution_year', 'npi_pollution', ['report_year'], unique=False)
    op.add_column('facilities', sa.Column('npi_id', sa.String(length=50), nullable=True))
    op.create_unique_constraint('uq_facilities_npi_id', 'facilities', ['npi_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop NPI-related changes
    op.drop_constraint('uq_facilities_npi_id', 'facilities', type_='unique')
    op.drop_column('facilities', 'npi_id')
    op.drop_index('idx_npi_pollution_year', table_name='npi_pollution')
    op.drop_index('idx_npi_pollution_substance', table_name='npi_pollution')
    op.drop_index('idx_npi_pollution_facility_year', table_name='npi_pollution')
    op.drop_table('npi_pollution')
    op.drop_table('npi_substances')
    op.drop_index('idx_npi_facilities_year', table_name='npi_facilities')
    op.drop_index('idx_npi_facilities_state', table_name='npi_facilities')
    op.drop_table('npi_facilities')
    # ### end Alembic commands ###
