# pylint: disable=no-member
"""
Add CMS fields for facilities and units

Revision ID: cb7207833fbd
Revises: 53a383ea9bcc
Create Date: 2025-09-05 03:05:25.360365

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'cb7207833fbd'
down_revision = '53a383ea9bcc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add facility fields
    op.add_column('facilities', sa.Column('osm_way_id', sa.Text(), nullable=True))
    op.add_column('facilities', sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    # Create spatial index if it doesn't exist
    op.execute("CREATE INDEX IF NOT EXISTS idx_facilities_location ON facilities USING gist (location)")
    op.add_column('units', sa.Column('capacity_maximum', sa.Numeric(precision=12, scale=4), nullable=True))
    op.add_column('units', sa.Column('capacity_storage', sa.Numeric(precision=12, scale=4), nullable=True))
    op.add_column('units', sa.Column('commencement_date_specificity', sa.Text(), nullable=True))
    op.add_column('units', sa.Column('closure_date_specificity', sa.Text(), nullable=True))
    op.add_column('units', sa.Column('expected_operation_date_specificity', sa.Text(), nullable=True))
    op.add_column('units', sa.Column('expected_operation_date_source', sa.Text(), nullable=True))
    op.add_column('units', sa.Column('expected_closure_date_specificity', sa.Text(), nullable=True))
    op.add_column('units', sa.Column('expected_closure_date_source', sa.Text(), nullable=True))
    op.add_column('units', sa.Column('construction_start_date', sa.DateTime(), nullable=True))
    op.add_column('units', sa.Column('construction_start_date_specificity', sa.Text(), nullable=True))
    op.add_column('units', sa.Column('construction_start_date_source', sa.Text(), nullable=True))
    op.add_column('units', sa.Column('construction_cost', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('units', sa.Column('construction_cost_source', sa.Text(), nullable=True))
    op.add_column('units', sa.Column('project_approval_date', sa.DateTime(), nullable=True))
    op.add_column('units', sa.Column('project_approval_date_specificity', sa.Text(), nullable=True))
    op.add_column('units', sa.Column('project_approval_date_source', sa.Text(), nullable=True))
    op.add_column('units', sa.Column('project_approval_lodgement_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove unit fields
    op.drop_column('units', 'project_approval_lodgement_date')
    op.drop_column('units', 'project_approval_date_source')
    op.drop_column('units', 'project_approval_date_specificity')
    op.drop_column('units', 'project_approval_date')
    op.drop_column('units', 'construction_cost_source')
    op.drop_column('units', 'construction_cost')
    op.drop_column('units', 'construction_start_date_source')
    op.drop_column('units', 'construction_start_date_specificity')
    op.drop_column('units', 'construction_start_date')
    op.drop_column('units', 'expected_closure_date_source')
    op.drop_column('units', 'expected_closure_date_specificity')
    op.drop_column('units', 'expected_operation_date_source')
    op.drop_column('units', 'expected_operation_date_specificity')
    op.drop_column('units', 'closure_date_specificity')
    op.drop_column('units', 'commencement_date_specificity')
    op.drop_column('units', 'capacity_storage')
    op.drop_column('units', 'capacity_maximum')
    
    # Remove facility fields
    op.execute("DROP INDEX IF EXISTS idx_facilities_location")
    op.drop_column('facilities', 'location')
    op.drop_column('facilities', 'osm_way_id')
    # ### end Alembic commands ###
