"""Schema v0.4.12

Revision ID: daf9150c9024
Revises: 
Create Date: 2020-07-07 12:07:06.155448

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "daf9150c9024"
down_revision = None
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_opennem():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bom_station")
    op.drop_table("bom_observation")
    op.drop_column("wem_facility_scada", "quantity")
    # ### end Alembic commands ###


def downgrade_opennem():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "wem_facility_scada",
        sa.Column(
            "quantity", sa.NUMERIC(), autoincrement=False, nullable=True
        ),
    )
    op.create_table(
        "bom_observation",
        sa.Column(
            "observation_time",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "station_id", sa.TEXT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "temp_apparent", sa.NUMERIC(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "temp_air", sa.NUMERIC(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "press_qnh", sa.NUMERIC(), autoincrement=False, nullable=True
        ),
        sa.Column("wind_dir", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "wind_spd", sa.NUMERIC(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["station_id"],
            ["bom_station.code"],
            name="fk_bom_observation_station_code",
        ),
        sa.PrimaryKeyConstraint(
            "observation_time", "station_id", name="bom_observation_pkey"
        ),
    )
    op.create_table(
        "bom_station",
        sa.Column("code", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("state", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("name", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("registered", sa.DATE(), autoincrement=False, nullable=True),
        sa.Column("lat", sa.NUMERIC(), autoincrement=False, nullable=True),
        sa.Column("lng", sa.NUMERIC(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("code", name="bom_station_pkey"),
    )
    # ### end Alembic commands ###
