# pylint: disable=no-member
"""
AggregateNetworkFlows

Revision ID: f15cca4d8584
Revises: 9956c679a0f6
Create Date: 2021-09-29 23:08:33.338810

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "f15cca4d8584"
down_revision = "9956c679a0f6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "at_network_flows",
        sa.Column(
            "trading_interval",
            postgresql.TIMESTAMP(timezone=True),
            nullable=False,
        ),
        sa.Column("network_id", sa.Text(), nullable=False),
        sa.Column("network_region", sa.Text(), nullable=True),
        sa.Column("energy_imports", sa.Numeric(), nullable=True),
        sa.Column("energy_exports", sa.Numeric(), nullable=True),
        sa.Column("emissions_imports", sa.Numeric(), nullable=True),
        sa.Column("emissions_exports", sa.Numeric(), nullable=True),
        sa.ForeignKeyConstraint(
            ["network_id"],
            ["network.code"],
            name="fk_at_facility_daily_network_code",
        ),
        sa.PrimaryKeyConstraint("trading_interval", "network_id"),
    )
    op.create_index(
        "idx_at_facility_daily_network_id_trading_interval",
        "at_network_flows",
        ["network_id", sa.text("trading_interval DESC")],
        unique=False,
    )
    op.create_index(
        "idx_at_facility_daily_trading_interval_facility_code",
        "at_network_flows",
        ["trading_interval", "network_id", "network_region"],
        unique=False,
    )
    op.create_index(
        op.f("ix_at_network_flows_network_id"),
        "at_network_flows",
        ["network_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_at_network_flows_network_region"),
        "at_network_flows",
        ["network_region"],
        unique=False,
    )
    op.create_index(
        op.f("ix_at_network_flows_trading_interval"),
        "at_network_flows",
        ["trading_interval"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_at_network_flows_trading_interval"),
        table_name="at_network_flows",
    )
    op.drop_index(
        op.f("ix_at_network_flows_network_region"),
        table_name="at_network_flows",
    )
    op.drop_index(
        op.f("ix_at_network_flows_network_id"), table_name="at_network_flows"
    )
    op.drop_index(
        "idx_at_facility_daily_trading_interval_facility_code",
        table_name="at_network_flows",
    )
    op.drop_index(
        "idx_at_facility_daily_network_id_trading_interval",
        table_name="at_network_flows",
    )
    op.drop_table("at_network_flows")
    # ### end Alembic commands ###
