# pylint: disable=no-member
"""
clean up balancing summary, indexes and other tables

Revision ID: a3fa44a8bf4d
Revises: 338b893d068b
Create Date: 2024-01-10 17:52:31.537606

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a3fa44a8bf4d"
down_revision = "338b893d068b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_balancing_summary_network_code",
        "balancing_summary",
        type_="foreignkey",
    )
    op.drop_column("balancing_summary", "created_at")
    op.drop_column("balancing_summary", "created_by")
    op.drop_column("balancing_summary", "updated_at")
    op.drop_index(
        "idx_facility_scada_network_id_trading_interval",
        table_name="facility_scada",
    )
    op.drop_constraint(
        "fk_balancing_summary_network_code",
        "facility_scada",
        type_="foreignkey",
    )

    for index in [
        "idx_bom_observation_month_awst",
        "idx_bom_observation_month_aest",
        "idx_bom_observation_day_aest",
        "idx_bom_observation_day_awst",
    ]:
        op.drop_index(index, table_name="bom_observation")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "fk_balancing_summary_network_code",
        "facility_scada",
        "network",
        ["network_id"],
        ["code"],
    )
    op.create_index(
        "idx_facility_scada_network_id_trading_interval",
        "facility_scada",
        ["network_id", sa.text("trading_interval DESC")],
        unique=False,
    )
    op.add_column(
        "balancing_summary",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "balancing_summary",
        sa.Column("created_by", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "balancing_summary",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_foreign_key(
        "fk_balancing_summary_network_code",
        "balancing_summary",
        "network",
        ["network_id"],
        ["code"],
    )
    # ### end Alembic commands ###
