name: Auto Promote to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      skip_tests:
        description: 'Skip tests before promotion'
        required: false
        default: false
        type: boolean

jobs:
  test-and-promote:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install dependencies
        run: |
          uv sync
          
      - name: Run tests
        if: ${{ !inputs.skip_tests }}
        run: |
          uv run pytest tests/ -v
          
      - name: Create PR to production
        if: success()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Check if PR already exists
          existing_pr=$(gh pr list --base production --head main --json number --jq '.[0].number')
          
          if [ -z "$existing_pr" ]; then
            gh pr create \
              --base production \
              --head main \
              --title "🚀 Auto-promote main to production" \
              --body "## Automated Production Promotion
          
          This PR automatically promotes tested changes from \`main\` to \`production\`.
          
          ### Pre-promotion checks:
          - ✅ All tests passed
          - ✅ Code quality checks passed
          
          **Review required before merge**" \
              --label "auto-promotion" \
              --label "production"
          else
            echo "PR #$existing_pr already exists from main to production"
          fi
